FROM node:20-alpine AS build-frontend
WORKDIR /frontend
COPY frontend/package*.json ./
RUN npm ci
COPY frontend ./
COPY prod.env .env
ENV VITE_API_URL=/api
RUN npm run build

FROM nginx:1.25-alpine
COPY --from=build-frontend /frontend/dist /usr/share/nginx/html
# nginx.conf will be mounted via volume from docker-compose.prod.yml
EXPOSE 80
EXPOSE 443
