version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  postgres:
    image: postgres:15-alpine
    container_name: antiquar-db
    env_file:
      - ./prod.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: antiquar-backend
    env_file:
      - ./prod.env
    environment:
      NODE_ENV: production
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: antiquar-minio
    env_file:
      - ./prod.env
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
    networks:
      - app-network
    restart: unless-stopped

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    container_name: antiquar-proxy
    env_file:
      - ./prod.env
    ports:
      - "80:80"  # ТОЛЬКО порт 80, без 443
    depends_on:
      - backend
    volumes:
      - ./nginx-simple.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    restart: unless-stopped
